- hosts: all
  remote_user: root
  tasks:
  - name: create nginx directory
    file:
      path: "/opt/nginx"
      state: directory
      mode: 0755
  - name: create nginx conf.d directory
    file:
      path: "/opt/nginx/conf.d"
      state: directory
      mode: 0755
  - name: create nginx data directory
    file:
      path: "/opt/nginx/data"
      state: directory
      mode: 0755
  - name: create nginx socks directory
    file:
      path: "/opt/nginx/socks"
      state: directory
      mode: 0777
  - name: create nginx letsencrypt directory
    file:
      path: "/opt/nginx/letsencrypt"
      state: directory
      mode: 0755
  - name: create nginx certbot_root directory
    file:
      path: "/opt/nginx/certbot_root"
      state: directory
      mode: 0755
  - name: deploy dockerfile context
    synchronize:
      src: "context/"
      dest: "/opt/nginx/"
      owner: no
      group: no
  - name: build & deploy container
    docker_service:
      build: yes
      project_src: "/opt/nginx"
  - name: cron job for renewing certificates
    cron:
      cron_file: nginx_letsencrypt_certs
      user: root
      name: "renew letsencrypt certs"
      job: >-
        docker run --rm
        -v /opt/nginx/certbot_root:/webroot
        -v /opt/nginx/letsencrypt:/etc/letsencrypt
        certbot/certbot renew -n
      hour: "0"
      minute: "0"
